/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SopRouteImport } from './routes/sop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProsedurRouteImport } from './routes/prosedur'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SopKategoriRouteImport } from './routes/sop.$kategori'
import { Route as QuizLevelRouteImport } from './routes/quiz.$level'
import { Route as ProsedurStepRouteImport } from './routes/prosedur.$step'
import { Route as KnowledgeLevelRouteImport } from './routes/knowledge.$level'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminToolsRouteImport } from './routes/admin.tools'
import { Route as AdminSopRouteImport } from './routes/admin.sop'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuizRouteImport } from './routes/admin.quiz'
import { Route as AdminProceduresRouteImport } from './routes/admin.procedures'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SopRoute = SopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsedurRoute = ProsedurRouteImport.update({
  id: '/prosedur',
  path: '/prosedur',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SopKategoriRoute = SopKategoriRouteImport.update({
  id: '/$kategori',
  path: '/$kategori',
  getParentRoute: () => SopRoute,
} as any)
const QuizLevelRoute = QuizLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => QuizRoute,
} as any)
const ProsedurStepRoute = ProsedurStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => ProsedurRoute,
} as any)
const KnowledgeLevelRoute = KnowledgeLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSopRoute = AdminSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizRoute = AdminQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProceduresRoute = AdminProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/contact': typeof ContactRoute
  '/informasi': typeof InformasiRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/prosedur': typeof ProsedurRouteWithChildren
  '/quiz': typeof QuizRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sop': typeof SopRouteWithChildren
  '/tools': typeof ToolsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sop': typeof AdminSopRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/knowledge/$level': typeof KnowledgeLevelRoute
  '/prosedur/$step': typeof ProsedurStepRoute
  '/quiz/$level': typeof QuizLevelRoute
  '/sop/$kategori': typeof SopKategoriRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/contact': typeof ContactRoute
  '/informasi': typeof InformasiRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/prosedur': typeof ProsedurRouteWithChildren
  '/quiz': typeof QuizRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sop': typeof SopRouteWithChildren
  '/tools': typeof ToolsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sop': typeof AdminSopRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/knowledge/$level': typeof KnowledgeLevelRoute
  '/prosedur/$step': typeof ProsedurStepRoute
  '/quiz/$level': typeof QuizLevelRoute
  '/sop/$kategori': typeof SopKategoriRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRoute
  '/contact': typeof ContactRoute
  '/informasi': typeof InformasiRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/maintenance': typeof MaintenanceRoute
  '/prosedur': typeof ProsedurRouteWithChildren
  '/quiz': typeof QuizRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sop': typeof SopRouteWithChildren
  '/tools': typeof ToolsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sop': typeof AdminSopRoute
  '/admin/tools': typeof AdminToolsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/knowledge/$level': typeof KnowledgeLevelRoute
  '/prosedur/$step': typeof ProsedurStepRoute
  '/quiz/$level': typeof QuizLevelRoute
  '/sop/$kategori': typeof SopKategoriRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/contact'
    | '/informasi'
    | '/knowledge'
    | '/maintenance'
    | '/prosedur'
    | '/quiz'
    | '/sitemap.xml'
    | '/sop'
    | '/tools'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/knowledge'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/procedures'
    | '/admin/quiz'
    | '/admin/settings'
    | '/admin/sop'
    | '/admin/tools'
    | '/admin/users'
    | '/artikel/$slug'
    | '/knowledge/$level'
    | '/prosedur/$step'
    | '/quiz/$level'
    | '/sop/$kategori'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/contact'
    | '/informasi'
    | '/knowledge'
    | '/maintenance'
    | '/prosedur'
    | '/quiz'
    | '/sitemap.xml'
    | '/sop'
    | '/tools'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/knowledge'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/procedures'
    | '/admin/quiz'
    | '/admin/settings'
    | '/admin/sop'
    | '/admin/tools'
    | '/admin/users'
    | '/artikel/$slug'
    | '/knowledge/$level'
    | '/prosedur/$step'
    | '/quiz/$level'
    | '/sop/$kategori'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai'
    | '/contact'
    | '/informasi'
    | '/knowledge'
    | '/maintenance'
    | '/prosedur'
    | '/quiz'
    | '/sitemap.xml'
    | '/sop'
    | '/tools'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/knowledge'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/procedures'
    | '/admin/quiz'
    | '/admin/settings'
    | '/admin/sop'
    | '/admin/tools'
    | '/admin/users'
    | '/artikel/$slug'
    | '/knowledge/$level'
    | '/prosedur/$step'
    | '/quiz/$level'
    | '/sop/$kategori'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRoute
  ContactRoute: typeof ContactRoute
  InformasiRoute: typeof InformasiRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MaintenanceRoute: typeof MaintenanceRoute
  ProsedurRoute: typeof ProsedurRouteWithChildren
  QuizRoute: typeof QuizRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SopRoute: typeof SopRouteWithChildren
  ToolsRoute: typeof ToolsRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop': {
      id: '/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof SopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosedur': {
      id: '/prosedur'
      path: '/prosedur'
      fullPath: '/prosedur'
      preLoaderRoute: typeof ProsedurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sop/$kategori': {
      id: '/sop/$kategori'
      path: '/$kategori'
      fullPath: '/sop/$kategori'
      preLoaderRoute: typeof SopKategoriRouteImport
      parentRoute: typeof SopRoute
    }
    '/quiz/$level': {
      id: '/quiz/$level'
      path: '/$level'
      fullPath: '/quiz/$level'
      preLoaderRoute: typeof QuizLevelRouteImport
      parentRoute: typeof QuizRoute
    }
    '/prosedur/$step': {
      id: '/prosedur/$step'
      path: '/$step'
      fullPath: '/prosedur/$step'
      preLoaderRoute: typeof ProsedurStepRouteImport
      parentRoute: typeof ProsedurRoute
    }
    '/knowledge/$level': {
      id: '/knowledge/$level'
      path: '/$level'
      fullPath: '/knowledge/$level'
      preLoaderRoute: typeof KnowledgeLevelRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tools': {
      id: '/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sop': {
      id: '/admin/sop'
      path: '/sop'
      fullPath: '/admin/sop'
      preLoaderRoute: typeof AdminSopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz': {
      id: '/admin/quiz'
      path: '/quiz'
      fullPath: '/admin/quiz'
      preLoaderRoute: typeof AdminQuizRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procedures': {
      id: '/admin/procedures'
      path: '/procedures'
      fullPath: '/admin/procedures'
      preLoaderRoute: typeof AdminProceduresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProceduresRoute: typeof AdminProceduresRoute
  AdminQuizRoute: typeof AdminQuizRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSopRoute: typeof AdminSopRoute
  AdminToolsRoute: typeof AdminToolsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProceduresRoute: AdminProceduresRoute,
  AdminQuizRoute: AdminQuizRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSopRoute: AdminSopRoute,
  AdminToolsRoute: AdminToolsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeLevelRoute: typeof KnowledgeLevelRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeLevelRoute: KnowledgeLevelRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ProsedurRouteChildren {
  ProsedurStepRoute: typeof ProsedurStepRoute
}

const ProsedurRouteChildren: ProsedurRouteChildren = {
  ProsedurStepRoute: ProsedurStepRoute,
}

const ProsedurRouteWithChildren = ProsedurRoute._addFileChildren(
  ProsedurRouteChildren,
)

interface QuizRouteChildren {
  QuizLevelRoute: typeof QuizLevelRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizLevelRoute: QuizLevelRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

interface SopRouteChildren {
  SopKategoriRoute: typeof SopKategoriRoute
}

const SopRouteChildren: SopRouteChildren = {
  SopKategoriRoute: SopKategoriRoute,
}

const SopRouteWithChildren = SopRoute._addFileChildren(SopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRoute,
  ContactRoute: ContactRoute,
  InformasiRoute: InformasiRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MaintenanceRoute: MaintenanceRoute,
  ProsedurRoute: ProsedurRouteWithChildren,
  QuizRoute: QuizRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SopRoute: SopRouteWithChildren,
  ToolsRoute: ToolsRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
