
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS tagline text DEFAULT 'Quality Control, Simplified.',
  ADD COLUMN IF NOT EXISTS text_color text DEFAULT '#0F172A',
  ADD COLUMN IF NOT EXISTS muted_color text DEFAULT '#64748B',
  ADD COLUMN IF NOT EXISTS keywords text,
  ADD COLUMN IF NOT EXISTS og_title text,
  ADD COLUMN IF NOT EXISTS og_description text,
  ADD COLUMN IF NOT EXISTS canonical_url text,
  ADD COLUMN IF NOT EXISTS website_url text,
  ADD COLUMN IF NOT EXISTS hero_title text DEFAULT 'Tingkatkan Standar QC Laptop & MacBook Anda',
  ADD COLUMN IF NOT EXISTS hero_subtitle text DEFAULT 'Panduan praktis, akurat, dan efisien untuk tim Quality Control modern.',
  ADD COLUMN IF NOT EXISTS cta_text text DEFAULT 'Mulai Sekarang',
  ADD COLUMN IF NOT EXISTS default_landing text DEFAULT 'beranda',
  ADD COLUMN IF NOT EXISTS show_main_nav boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_navbar_search boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_ai_widget boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_music_widget boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS language text DEFAULT 'id',
  ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'Asia/Jakarta',
  ADD COLUMN IF NOT EXISTS maintenance_mode boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS enable_ai_widget boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS enable_music_widget boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS ga_id text,
  ADD COLUMN IF NOT EXISTS meta_pixel_id text,
  ADD COLUMN IF NOT EXISTS search_console_token text,
  ADD COLUMN IF NOT EXISTS analytics_api_key text;
